(cl:defpackage hector_gazebo_plugins-srv
  (:use )
  (:export
   "SETBIAS"
   "<SETBIAS-REQUEST>"
   "SETBIAS-REQUEST"
   "<SETBIAS-RESPONSE>"
   "SETBIAS-RESPONSE"
   "SETREFERENCEGEOPOSE"
   "<SETREFERENCEGEOPOSE-REQUEST>"
   "SETREFERENCEGEOPOSE-REQUEST"
   "<SETREFERENCEGEOPOSE-RESPONSE>"
   "SETREFERENCEGEOPOSE-RESPONSE"
  ))

